// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLXYPctmNK8NZu3SoD19XfYxy571JQUb4',
    appId: '1:588222942568:web:8fe0bbff2ab4b529a2dadd',
    messagingSenderId: '588222942568',
    projectId: 'moon-ed708',
    authDomain: 'moon-ed708.firebaseapp.com',
    storageBucket: 'moon-ed708.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxYm-sSU4UCJQ4PNPkuHw6mO-W-8g6B1c',
    appId: '1:588222942568:android:e2db326442035586a2dadd',
    messagingSenderId: '588222942568',
    projectId: 'moon-ed708',
    storageBucket: 'moon-ed708.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJbWmz5iveDjv6lSdvxIU_IV_SWBKkg6U',
    appId: '1:588222942568:ios:5c8c99ad47ec0af6a2dadd',
    messagingSenderId: '588222942568',
    projectId: 'moon-ed708',
    storageBucket: 'moon-ed708.appspot.com',
    iosClientId: '588222942568-2e57p4s0v4rtt8lq9a3korvi7obhb1iv.apps.googleusercontent.com',
    iosBundleId: 'com.example.moon2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJbWmz5iveDjv6lSdvxIU_IV_SWBKkg6U',
    appId: '1:588222942568:ios:5c8c99ad47ec0af6a2dadd',
    messagingSenderId: '588222942568',
    projectId: 'moon-ed708',
    storageBucket: 'moon-ed708.appspot.com',
    iosClientId: '588222942568-2e57p4s0v4rtt8lq9a3korvi7obhb1iv.apps.googleusercontent.com',
    iosBundleId: 'com.example.moon2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLXYPctmNK8NZu3SoD19XfYxy571JQUb4',
    appId: '1:588222942568:web:e97487548e4e503da2dadd',
    messagingSenderId: '588222942568',
    projectId: 'moon-ed708',
    authDomain: 'moon-ed708.firebaseapp.com',
    storageBucket: 'moon-ed708.appspot.com',
  );
}
